### ISSUE TITLE
404 not found when installing

### ISSUE THREAD

**Issue by neohunter** [mablack/cordova-diagnostic-plugin#2]
I"m tyring to install this but appears:

 # cordova plugin add cordova.plugins.diagnostic

Fetching plugin "cordova.plugins.diagnostic" via plugin registry
Error: 404 Not Found: cordova.plugins.diagnostic
    at RegClient.<anonymous> (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:304:14)
    at Request._callback (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:246:65)
    at Request.self.callback (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/request/request.js:236:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/request/request.js:1142:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/request/request.js:1096:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:442:13)

**Comment by mablack** [comment]
Hi @neohunter, 

this isn't the "official" repository for the Diagnostic plugin, so it's not listed in the Cordova plugin registry. It looks like the version that *was* listed in the registry has been removed, hence the 404.

You should be able to install the version from this repository by using the GitHub URL:
```cordova plugin add https://github.com/mablack/cordova-diagnostic-plugin```

The command to remove the plugin just requires the plugin name:
```cordova plugin remove cordova.plugins.diagnostic```
